from django.urls import path
from . import views

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('tipos/', views.lista_tipos, name='lista_tipos'),
    path('tipos/nuevo/', views.crear_tipo, name='crear_tipo'),
    path('tipos/editar/<int:id>/', views.editar_tipo, name='editar_tipo'),
    path('tipos/eliminar/<int:id>/', views.eliminar_tipo, name='eliminar_tipo'),
    path('generos/', views.lista_generos, name='lista_generos'),
    path('generos/nuevo/', views.crear_genero, name='crear_genero'),
    path('generos/editar/<int:id>/', views.editar_genero, name='editar_genero'),
    path('generos/eliminar/<int:id>/', views.eliminar_genero, name='eliminar_genero'),
    path('idiomas/', views.lista_idiomas, name='lista_idiomas'),
    path('idiomas/nuevo/', views.crear_idioma, name='crear_idioma'),
    path('idiomas/editar/<int:id>/', views.editar_idioma, name='editar_idioma'),
    path('idiomas/eliminar/<int:id>/', views.eliminar_idioma, name='eliminar_idioma'),
    path('articulos/', views.lista_articulos, name='lista_articulos'),
    path('articulos/nuevo/', views.crear_articulo, name='crear_articulo'),
    path('articulos/editar/<int:id>/', views.editar_articulo, name='editar_articulo'),
    path('articulos/eliminar/<int:id>/', views.eliminar_articulo, name='eliminar_articulo'),
    path('clientes/', views.lista_clientes, name='lista_clientes'),
    path('clientes/nuevo/', views.crear_cliente, name='crear_cliente'),
    path('clientes/editar/<int:id>/', views.editar_cliente, name='editar_cliente'),
    path('clientes/eliminar/<int:id>/', views.eliminar_cliente, name='eliminar_cliente'),
    path('empleados/', views.lista_empleados, name='lista_empleados'),
    path('empleados/nuevo/', views.crear_empleado, name='crear_empleado'),
    path('empleados/editar/<int:id>/', views.editar_empleado, name='editar_empleado'),
    path('empleados/eliminar/<int:id>/', views.eliminar_empleado, name='eliminar_empleado'),
    path('rentas/', views.lista_rentas, name='lista_rentas'),
    path('rentas/nuevo/', views.crear_renta, name='crear_renta'),
    path('rentas/editar/<int:id>/', views.editar_renta, name='editar_renta'),
    path('rentas/eliminar/<int:id>/', views.eliminar_renta, name='eliminar_renta'),
]