# Generated by Django 6.0.3 on 2026-03-13 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoClubApp', '0004_idioma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('renta_x_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_renta', models.IntegerField()),
                ('monto_entrega_tardia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoClubApp.idioma')),
                ('tipo_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoClubApp.tipoarticulo')),
            ],
        ),
    ]
