# Generated by Django 6.0.3 on 2026-03-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoClubApp', '0005_articulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=20)),
                ('tarjeta_credito', models.CharField(max_length=25)),
                ('limite_credito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_persona', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
