# Generated by Django 6.0.3 on 2026-03-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoClubApp', '0006_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=20)),
                ('tanda_labor', models.CharField(choices=[('M', 'Matutina'), ('V', 'Vespertina'), ('N', 'Nocturna')], max_length=1)),
                ('porciento_comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
