# Generated by Django 6.0.3 on 2026-03-13 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoClubApp', '0007_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_renta', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('monto_x_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_dias', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('R', 'Rentado'), ('D', 'Devuelto')], default='R', max_length=1)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoClubApp.articulo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoClubApp.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoClubApp.empleado')),
            ],
        ),
    ]
